name: "aws-secrets-wrapper"
description: "injects aws-secrets-wrapper into the workflow, provides binary for Docker builds via target 'aws-secrets-wrapper:builder'"
author: ribonred <ribonred@gmail.com>
branding:
  icon: "layers"
  color: "orange"
inputs:
  aws_access_key:
    description: "aws access key"
    required: true
  aws_secret_key:
    description: "aws secret key"
    required: true
  aws_region:
    description: "aws region"
    required: true
  aws_s3_cache_bucket:
    description: "S3 bucket for caching secrets"
    required: false
  image_tag:
    description: "The tag of the aws-secret-wrapper image to use"
    required: false
    default: "latest"
outputs:
  binary:
    description: "Path to the aws-secrets-wrapper binary"
runs:
  using: "docker"
  image: "docker://ghcr.io/ribonred/aws-secret-wrapper:latest"
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
    AWS_REGION: ${{ inputs.aws_region }}
    S3_CACHE_BUCKET: ${{ inputs.s3_cache_bucket }}