name: Release
on:
  release:
    types: [created]

jobs:
  tag-major-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get major version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=${VERSION%%.*}
          echo "major_version=${MAJOR_VERSION}" >> $GITHUB_OUTPUT
        
      - name: Update major version tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -fa v${{ steps.get_version.outputs.major_version }} -m "Update v${{ steps.get_version.outputs.major_version }} tag"
          git push origin v${{ steps.get_version.outputs.major_version }} --force